language: python
group: deprecated-2017Q2 # circumvent a travis bug: https://github.com/travis-ci/travis-ci/issues/8048
sudo: required
dist: trusty

# safelist
branches:
  only:
  - master

matrix:
    include:
        - python: "2.7_with_system_site_packages"
          env: PY=2.7 PYTHONPATH=$PYTHONPATH:/opt/mantidnightly/bin
        - python: "3.4_with_system_site_packages"
          env: PY=3.4 PYTHONPATH=$PYTHONPATH:/opt/mantidnightly-python3/bin

cache: pip

before_install: buildscripts/install_mantidnightly.sh ${PY}

install: buildscripts/install.sh

script: buildscripts/run.sh

after_success:
  - coveralls
