language: python
group: deprecated-2017Q2 # circumvent a travis bug: https://github.com/travis-ci/travis-ci/issues/8048
sudo: required
dist: trusty

# safelist
branches:
  only:
  - master

matrix:
    include:
        - python: "2.7_with_system_site_packages"
          env: PYTHONPATH=$PYTHONPATH:/opt/mantidnightly/bin

cache: pip

install: buildscripts/install.sh

script: buildscripts/run.sh

after_success:
  - coveralls
