language: python
python:
  - "2.7"
# command to install dependencies
install: 
  pip install -r pip-requirements.txt
  export MSLICE_PLOT_WINDOWS="TEST"
# command to run tests
script: 
  nosetests -v --with-coverage --cover-min-percentage=80 --cover-package=presenters,plotting.figuremanager

after_success:
  coveralls