language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install 'mock>=2.0.0'" --force-reinstall
# command to run tests
script: "python -m unittest discover -s tests -p '*test.py'"