language: python
python:
  - "2.7"
# command to install dependencies
install: 
  pip install -r pip-requirements.txt

# command to run tests
script: 
  nosetests --with-coverage --cover-package=presenter,plotting.FigureManager

after_success:
  coveralls