language: python
python:
  - "2.7"
# command to install dependencies
install: 
  pip install -r pip-requirements.txt

# command to run tests
script: 
  nosetests -v --with-coverage --cover-min-percentage=80 --cover-package=presenters,plotting.figuremanager --exclude-dir=presenters/interfaces

after_success:
  coveralls