language: python

sudo: required
dist: trusty

python:
  # See https://github.com/travis-ci/travis-ci/issues/2219#issuecomment-41804942
  - "2.7_with_system_site_packages" # for pyqt4

cache: pip

before_install:
  - sudo apt-add-repository ppa:mantid/mantid -y && sudo apt-get update -q
  # Download deb file from sourceforge as it's far quicker that the ISIS repo
  - sudo apt-get install gdebi -y
  - wget https://sourceforge.net/projects/mantid/files/Nightly/ -O /tmp/index.html
  - export mantiddeb=$(grep mantidnightly /tmp/index.html |grep amd64.deb | sed s/.*man/man/ | sed s/.deb.*/.deb/ | head -n1)
  - wget http://downloads.sourceforge.net/project/mantid/Nightly/$mantiddeb -O /tmp/mtn.deb
  - sudo gdebi --option=APT::Get::force-yes=1,APT::Get::Assume-Yes=1 -n /tmp/mtn.deb
  - mkdir $HOME/.mantid && echo -e "UpdateInstrumentDefinitions.OnStartup=0\nCheckMantidVersion.OnStartup=0\n" > $HOME/.mantid/Mantid.user.properties

install:
  - pip install -r setup-requirements.txt -r install-requirements.txt -r test-requirements.txt coveralls

env:
  - PYTHONPATH=$PYTHONPATH:/opt/mantidnightly/bin

script:
  - set -e
  - python setup.py flake8
  - python setup.py nosetests

after_success:
  - coveralls
