language: python
python:
  - "2.7"
# command to install dependencies
install: 
  pip install -r pip-requirements.txt

# command to run tests
script: 
  nosetests -v --with-coverage --cover-package=presenters,plotting.figuremanager

after_success:
  coveralls